@baseUrl = http://localhost:5000
@apiUrl = {{baseUrl}}/api

# Authentification
@auth = {{apiUrl}}/auth
@signup = {{auth}}/signup
@login = {{auth}}/login
@logout = {{auth}}/logout
@me = {{auth}}/me

# Messages
@messages = {{apiUrl}}/messages
@send = {{messages}}/send
@conversations = {{messages}}/conversations

# Users
@john = /cm1l9kn09000014dysgmsfqoy
@jane = /cm1laz4eo0000gyx25ot7o7re

###
POST {{signup}}
Content-Type: application/json

{
    "fullName": "Jane Doe",
    "username": "janedoe",
    "password": "654321",
    "confirmPassword": "654321",
    "gender": "female"
    
}

###
POST {{signup}}
Content-Type: application/json

{
    "fullName": "John Doe",
    "username": "johnndoe",
    "password": "123456",
    "confirmPassword": "123456",
    "gender": "male"
    
}

###
POST {{signup}}
Content-Type: application/json

{
    "fullName": "Toto Toto",
    "username": "toto",
    "password": "toto",
    "confirmPassword": "tata",
    "gender": "male"   
}

###
POST {{login}}
Content-Type: application/json

{
    "username": "janedoe",
    "password": "654321"
    
}


###
POST {{login}}
Content-Type: application/json

{
    "username": "johndoe",
    "password": "123456"
    
}

###
POST {{logout}}

###
GET {{me}}

###
POST {{send}}{{john}}
Content-Type: application/json

{
    "message": "Hi jane, this is my second message !"    
}

###
GET {{messages}}{{john}}

###
GET {{conversations}}

