@baseUrl = http://localhost:5000
@apiUrl = {{baseUrl}}/api

@signup = {{apiUrl}}/auth/signup

###
POST {{signup}}
Content-Type: application/json

{
    "fullName": "Jane Doe",
    "username": "janedoe",
    "password": "654321",
    "confirmPassword": "654321",
    "gender": "female"
    
}
